#!/usr/bin/env python3 
import sys
import random

def help_function():
  print(help_message)

help_message = """
usage: xkcdpwgen [-h] [-w WORDS] [-c CAPS] [-n NUMBERS] [-s SYMBOLS]
                
Generate a secure, memorable password using the XKCD method
                
optional arguments:
    -h, --help            show this help message and exit
    -w WORDS, --words WORDS
                          include WORDS words in the password (default=4)
    -c CAPS, --caps CAPS  capitalize the first letter of CAPS random words
                          (default=0)
    -n NUMBERS, --numbers NUMBERS
                          insert NUMBERS random numbers in the password
                          (default=0)
    -s SYMBOLS, --symbols SYMBOLS
                          insert SYMBOLS random symbols in the password
                          (default=0)
"""

def no_arg():
    wordlist = open("words.txt").read().splitlines()

    pick_four = random.sample(wordlist, 4)

    pwd = ''.join(pick_four).lower()

    print(pwd)


def main():
  no_arg()

if __name__ == "__main__":
  main() 

